version: "3.9"

services:
  web:
    build: web
    container_name: web
    environment:
      PGHOST:
      PGUSER:
      PGPASSWORD:
    volumes:
      - .:/workspace:cached
    ports:
      - 3000:3000
    tty: true
  server:
    build: server
    container_name: server
    environment:
      PGHOST:
      PGUSER:
      PGPASSWORD:
      MQTTUSER:
      MQTTPASSWORD:
    volumes:
      - .:/workspace:cached
    tty: true
  broker:
    image: eclipse-mosquitto
    container_name: broker
    volumes:
      - ./broker:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
  db:
    image: postgres:alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
    ports:
      - 5432:5432

networks:
  thinkleg-network:
    external: true
