version: "3.9"

services:
  web:
    build: web
    container_name: web
    volumes:
      - .:/workspace:cached
    ports:
      - 3000:3000
    tty: true
  server:
    build: server
    container_name: server
    volumes:
      - .:/workspace:cached
    ports:
      - 3001:3001
    tty: true
  broker:
    image: eclipse-mosquitto
    container_name: broker
    volumes:
      - ./broker:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    tty: true

networks:
  thinkleg-network:
    external: true