import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import useSWR, { useSWRConfig } from 'swr';
import RealtimeChart from '../components/realtimechart';

const fetcher = (url) => fetch(url).then((r) => r.json());

interface Data {
  x: number;
  y: number;
}

const Test: NextPage = () => {
  const [chartData, setchartData] = useState<Number[][2]>();
  const { mutate } = useSWRConfig();
  const { data, error } = useSWR(
    '/api/legdata/?device=test&limit=6000',
    fetcher
  );

  useEffect(() => {
    if (data) {
      setchartData(data);
    }
  }, [data]);

  useEffect(() => {
    const timer = setInterval(() => {
      mutate('/api/legdata/?device=test&limit=6000');
    }, 500);
    return () => clearInterval(timer);
  });

  return (
    <>
      <Head>
        <title>Test Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="app">
        <div className="row">
          {chartData && (
            <div className="mixed-chart">
              <RealtimeChart
                series={[{ name: 'test', data: chartData.slice(300) }]}
                range={3000}
              />
              <RealtimeChart
                series={[{ name: 'test', data: chartData }]}
                range={100000}
                height={100}
              />
            </div>
          )}
        </div>
      </div>
    </>
  );
};

export default Test;
