import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useRef, useState } from 'react';
import { io } from "socket.io-client";
import RealtimeChart from '../components/realtimechart';

interface Data { x: number, y: number; }

const Test: NextPage = () => {
  const [msg, setMsg] = useState('')
  const [data, setData] = useState({} as Data);

  useEffect(() => {
    const socket = io();
    socket.on('message', (msg) => {
      setMsg(msg);
      console.log(msg);
    });
    socket.on('connect', () => {
      console.log(socket.id);
      socket.emit("getData", '');
    });

    return () => {
      socket.close();
    };
  }, []);

  return (
    <>
      <Head>
        <title>Test Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="app">
        <div className="row">
          <div className="mixed-chart">
            <p>{msg}</p>
            <RealtimeChart series={[{ name: "test", data: [] }]} />
          </div>
        </div>
      </div>
    </>
  );
};

export default Test;
