import type { NextPage } from 'next'
import Head from 'next/head'
import dynamic from 'next/dynamic'
import ApexChart from 'apexcharts'

const Chart = dynamic(() => import('react-apexcharts'), { ssr: false })

const Test: NextPage = () => {
  const options = {
    chart: {
      type: 'line'
    },
    xaxis: {
      categories: [1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999]
    }
  } as ApexChart.ApexOptions
  const series = [{
    name: 'sales',
    data: [30, 40, 35, 50, 49, 60, 70, 91, 125]
  }]

  return (
    <>
      <Head>
        <title>Test Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="app">
        <div className="row">
          <div className="mixed-chart">
            <Chart
              options={options}
              series={series}
              type="bar"
              width="500"
            />
          </div>
        </div>
      </div>
    </>
  )
}

export default Test
